// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDYKbU4WB5-sQlBBAkcD4jDMfWIlSHzzo',
    appId: '1:567131096056:web:36a9fad1d913b34b95cc0d',
    messagingSenderId: '567131096056',
    projectId: 'chat-app-f22a5',
    authDomain: 'chat-app-f22a5.firebaseapp.com',
    storageBucket: 'chat-app-f22a5.appspot.com',
    measurementId: 'G-VBWF3WG8LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzWMplGOExyHr6SuNLecVzzsZckRaeOO0',
    appId: '1:567131096056:android:fa5d6ce6117815f995cc0d',
    messagingSenderId: '567131096056',
    projectId: 'chat-app-f22a5',
    storageBucket: 'chat-app-f22a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJcEZivCHlqO7LkbAmwaO9_uJZi0CDTkU',
    appId: '1:567131096056:ios:597b04cdaebdadc295cc0d',
    messagingSenderId: '567131096056',
    projectId: 'chat-app-f22a5',
    storageBucket: 'chat-app-f22a5.appspot.com',
    iosBundleId: 'com.example.chatapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJcEZivCHlqO7LkbAmwaO9_uJZi0CDTkU',
    appId: '1:567131096056:ios:597b04cdaebdadc295cc0d',
    messagingSenderId: '567131096056',
    projectId: 'chat-app-f22a5',
    storageBucket: 'chat-app-f22a5.appspot.com',
    iosBundleId: 'com.example.chatapp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDYKbU4WB5-sQlBBAkcD4jDMfWIlSHzzo',
    appId: '1:567131096056:web:86642e6e0ab066f095cc0d',
    messagingSenderId: '567131096056',
    projectId: 'chat-app-f22a5',
    authDomain: 'chat-app-f22a5.firebaseapp.com',
    storageBucket: 'chat-app-f22a5.appspot.com',
    measurementId: 'G-81KY8TC1CE',
  );
}
